<?php
$adTable = <<< EOD
<script type="text/javascript"><!--
google_ad_client = "pub-9006330564002960";
google_ad_width = 728;
google_ad_height = 90;
google_ad_format = "728x90_as";
google_ad_type = "text_image";
google_ad_channel ="";
google_color_border = "000000";
google_color_bg = "FDEFD2";
google_color_bg = "f2ebc6";
google_color_bg = "E0E0E0";
google_color_link = "ffffff";
google_color_url = "008000";
google_color_text = "000000";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
EOD;


print "<center>";
//print "<div id=\"content\" onmouseover=\"reportEnter(event)\";>\n";
print "<div>\n";
print "&nbsp;\n";

print "<div>\n";
//print $adTable;
//print $adTable;
print "</div>\n";

print "</div>\n";
print "&nbsp;\n";

print "</center>";


?>
