<?php
$X_PUZZLE="パズル";

$X_PURCHASE="購入";
$X_DAVIDHILL="デイビッド・ヒル";
$X_ELLIPSE="楕円";
$X_FLOODFILL="洪水";
$X_GRITTY="グリット";
$X_DEEPDREAM="夢";

$X_NEWSPRINT="新聞";

$X_BOUNDBOX="画像の選択をアクティブに";

$X_MAGNIFY="拡大します";
$X_SKEW="スキュー";
$X_ENRICH="濃縮する";
$X_SKETCH="スケッチ";


$X_BEAUTY="美";

$X_BLEND="ブレンド";
$X_DOWNLOAD="ダウンロード";

$X_WEBCAM="ウェブカメラ";
$X_SNAPSHOT="カメラ";
$X_SNAPSHOT2="";

$X_VIEWIMAGE="画像を見る";
$X_STAINEDGLASS="ステンドグラス";
$X_CUT="カット";
$X_FACEOFF="顔";
$X_FACEHELP="(Use Your Mouse to Define the Face Area)";
$X_OVERLAY="オーバーレイ";

$X_ROLLIMAGE="転がる";
$X_REDUCECOLOR="色を減らす";
$X_GLITTER="輝き";
$X_GROOVY="グルービー";
$X_OUTLINE="概要";
$X_PEARL="真珠";
$X_SHAPE="形状";

$X_STENCIL="ステンシル";

$X_KALEIDOSCOPE="万華鏡";

$X_CAMERA="カメラ";

$X_HISTORY="の歴史";
$X_DAYS="日";

$X_RAINBOW="Rainbow";
$X_POPART="Pop Art";

$X_WARP ="ワープ";
$X_ENHANCE="強化";
$X_FORMAT ="フォーマット";
$X_GIF="GIF";
$X_JPG="JPG";
$X_PNG="PNG";
$X_BMP="BMP";
$X_ICO="ICO";
$X_INSTANTFIX="すぐに";
$X_HDR ="HDR";
$X_SMOOTH ="滑らかに";
$X_BLUR="ぼかし";
$X_TEXTURE ="テクスチャ";
$X_COLOR ="色";
$X_ADJUST="調整";
$X_MONOCHROME ="モノクローム";
$X_NEGATE ="否定";
$X_SEPIA ="セピア";
$X_TINT ="色合い";
$X_ACCENT ="アクセント";
$X_CONTRAST ="コントラスト";
$X_BRIGHTNESS ="明るさ";
$X_SHARPNESS ="シャープネス";
$X_SATURATION ="彩度";
$X_HUE ="色相";

$X_HIGHER ="高い";
$X_LOWER ="低い";

$X_EDIT="編集する";
$X_ROTATE="回転";
$X_INSTANTROTATE="即座に";
$X_ORIENT ="オリエンテーション";
$X_FLIPVERTICALLY ="垂直";
$X_FLIPHORIZONTALLY ="水平方向の";
$X_CROP ="トリミング";
$X_RECTANGULAR ="長方形";
$X_VIGNETTE ="ビネット";
$X_SHAVE="トリム";
$X_TRIM3 ="トリム3％";
$X_TRIM ="トリム";
$X_BORDER ="境界線";
$X_ARTFRAME ="アートフレーム";
$X_BLENDFRAME="混ぜる";
$X_EDGE3DUP ="+ エッジ 3D";
$X_EDGE3DDOWN ="- エッジ 3D";
$X_EDGE = "3D";
$X_BUTTON ="ボタン";
$X_LABEL ="ラベル";
$X_BORDERTEXT ="境界線のテキスト";
$X_STAMPTEXT ="スタンプテキスト";
$X_GLITTERTEXT ="キラキラテキスト";
$X_WATERMARK ="透かし";
$X_POSTER ="ポスター";
$X_RESIZE="リサイズ";
$X_RESIZEPERCENT ="%";
$X_RESIZEPIXELS ="ピクセル";
$X_THUMBNAIL ="サムネイル";
$X_FILEKBSIZE="ファイルサイズ";
$X_REDUCE="減らす";
$X_INSTANTREDUCE="即座に削減";


$X_MIX ="ミックス";
$X_ANIMATE ="アニメイト";
$X_FRAMEANIMATION ="アニメイト";
$X_VIBRATE="振動";
$X_SCROLL="スクロール";
$X_SPIN ="スピン";
$X_REFLECT="反映";
$X_PIMP ="ポン";
$X_DEFORM="変形";
$X_3DANIMATION ="3Dアニメーション";
$X_POWERMORPH ="モーフィング";
$X_THEMATRIX="マトリックス";
$X_COMBINE= "は結合";
$X_BLENDIMAGES ="ブレンド画像";
$X_COOKIE ="クッキー";
$X_JIGSAW="パズル";
$X_MONTAGE ="モンタージュ";
$X_WORLDMIX ="ワールドミックス";
$X_MAGAZINE ="雑誌";
$X_FIREANDRAIN ="ファイアー＆レイン";
$X_COLORSWAP ="スワップ";
$X_BLACKANDWHITE ="ブラックホワイト";
$X_COLORIZE="移す";
$X_COLORWASH ="ウォッシュ";
$X_BLEACH ="ブリーチ";
$X_HEATMAP="赤外線";
$X_AVATAR ="アバター";
$X_PHOTOTOCARTOON ="漫画";


$X_CREATE="作成";
$X_LAYER ="レイヤー";
$X_TRANSPARENT ="透明を";
$X_TRANSPARENTBATCH ="透明を+";
$X_TRANSLUCENT ="透明を";
$X_BEND ="ベンド";
$X_SWIRL ="渦巻き";
$X_IMPLODE="爆縮";
$X_EXPLODE="爆発";
$X_STRETCH ="ストレッチ";
$X_WAVE ="波動";
$X_MUTATE="変化する";
$X_MELT="はメルト";
$X_PIXELATE="ピクセル";
$X_SPLICE ="スプライス";
$X_FRACTAL ="フラクタル";
$X_TIMETUNNEL ="トンネル";
$X_FOSSILIZE="化石";
$X_3DSHAPE="形状 3D";
$X_ARTISTIC ="芸術";
$X_OILPAINT ="オイルペイント";
$X_PENCIL ="鉛筆";
$X_CHARCOAL ="炭";
$X_ABSTRACT ="抽象";
$X_BLACKLIGHT ="ブラックライト";
$X_PSYCHEDELIC ="サイケデリック";
$X_EMBOSS ="エンボス";
$X_ARTGALLERY ="アートギャラリー";
$X_FEELLUCKY ="ランダム";

$X_RETURNTOMAINPAGE ="メインページに戻る";
$X_LABEL ="ラベル";
$X_CONVERT="変換";
$X_SELECTED="選択";
$X_EFFECT ="効果";
$X_LEVEL ="レベル";
$X_LINE ="線";
$X_LOOP ="ループ";
$X_FONT ="フォント";
$X_FONTSIZE;
$X_FUZZ ="ファズ";
$X_LOW ="1";
$X_MEDIUM ="2";
$X_HIGH ="3";
$X_WIDTH ="幅";
$X_LENGTH ="長さ";
$X_REVERSEMORPHINGATEND ="逆";
$X_REVERSE="逆";


$X_CLICKTOLOADIMAGE ="をクリックして画像を読み込む";
$X_DIMENSIONS ="サイズ";
$X_COLORCOUNT ="色数";
$X_CLICKTOVIEWMAC ="";
$X_CLICKTOVIEWPC="";
$X_UNDO ="[使用ブラウザは元に戻すボタン]を";

$X_LOADIMAGE ="画像をアップロード";
$X_FILELOADED="ファイルが読み込ま";
$X_FROMCOMPUTER ="アップロードのコンピュータから";
//$X_FROMWEB ="ウェブからの負荷のURL（貼り付け";
$X_FROMWEB ="ウェブからの負荷のURL";
$LOAD_HELP ="ファイルの最大サイズ2.0MBのです";
$X_OR ="又は";
$X_LOAD ="アップロード";
$X_CLEAR ="取り消す";

$TRANS_HELP ="";
$X_SLOWNOTE ="オプションと画像の複雑さに応じて、この操作を実行する分かかることがあります";


$X_DIRECTION ="方向";
$X_FILE ="ファイル";
$X_FIRSTIMAGEWHOLE ="第1回画像全体";
$X_HEIGHT ="高さ";
$X_WIDTH ="幅";
$X_HOLES ="現実の穴";
$X_ORIENTATION ="オリエンテーション";
$X_POSITION ="位置";
$X_PRESERVEASPECTRATIOは="縦横比を維持";
$X_SELECTCOLOR ="色を選択";
$X_SEPARATION ="分離";


$X_SPEED="速度";
$X_AUTORESIZE="自動的にサイズ変更";
$X_SIZE="サイズ";
$X_BLENDIMAGE="画像";
$X_BLENDLEVEL="レベル";
$X_COLORTITLEANDBORDER = $X_PICKCOLOR="色";
$X_COLORBACKGROUND = $X_PICKBACKGROUNDCOLOR="背景色";
$X_TITLE="タイトル";
$X_COLORTEXT="テキストの色";
$X_PRESERVEASPECTRATIO="保持アスペクト比";

$X_GEOMETRIC="ジオメトリック";



?>
