<?php
$X_PUZZLE="퍼즐";

$X_PURCHASE="사다";
$X_DAVIDHILL="골동품";
$X_ELLIPSE="타원";
$X_FLOODFILL="홍수";
$X_GRITTY="모래";
$X_DEEPDREAM="꿈";

$X_NEWSPRINT="신문";

$X_BOUNDBOX="이미지 선택을 활성화";

$X_MAGNIFY="확대";
$X_SKEW="비뚤어 짐";
$X_ENRICH="풍성";
$X_SKETCH="스케치";


$X_BEAUTY="름다움";

$X_BLEND="혼합";
$X_DOWNLOAD="다운로드";

$X_WEBCAM="웹캠";
$X_SNAPSHOT="카메라";
$X_SNAPSHOT2="";


$X_VIEWIMAGE="이미지보기";
$X_STAINEDGLASS="착색 유리";
$X_CUT="절단";
$X_FACEOFF="얼굴";
$X_FACEHELP="(Use Your Mouse to Define the Face Area)";
$X_OVERLAY="오버레이";

$X_ROLLIMAGE="롤";
$X_REDUCECOLOR="색상 줄이기";
$X_GLITTER="반짝이다";
$X_GROOVY="당연하지";
$X_OUTLINE="개요";
$X_PEARL="진주";
$X_SHAPE="형성하다";

$X_STENCIL="원판";

$X_KALEIDOSCOPE="만화경";

$X_CAMERA="카메라";

$X_HISTORY="역사";
$X_DAYS="일";

$X_POPART="팝아트";

$X_WARP ="휘게하다";
$X_ENHANCE="높이다";
$X_FORMAT ="체재";
$X_GIF="GIF";
$X_JPG="JPG";
$X_PNG="PNG";
$X_BMP="BMP";
$X_ICO="ICO";
$X_INSTANTFIX="즉시 수정";
$X_HDR ="HDR";
$X_SMOOTH ="없애다";
$X_BLUR="흐림";
$X_TEXTURE ="직조하다";
$X_COLOR ="색";
$X_ADJUST="조정";
$X_MONOCHROME ="흑백의";
$X_NEGATE ="부정";
$X_SEPIA ="세피아";
$X_TINT ="색칠하다";
$X_ACCENT ="컬러 악센트";
$X_CONTRAST ="대조";
$X_BRIGHTNESS ="명도";
$X_SHARPNESS ="날카로움";
$X_SATURATION ="채도";
$X_HUE ="색조";

$X_HIGHER ="늘리다";
$X_LOWER ="줄이다";

$X_EDIT="편집하다";
$X_ROTATE="회전하다";
$X_INSTANTROTATE="회전 인스턴트";
$X_ORIENT ="정위";
$X_FLIPVERTICALLY ="수직으로 뒤집기";
$X_FLIPHORIZONTALLY ="수평으로 뒤집기";
$X_CROP ="작물 이미지";
$X_RECTANGULAR ="직사각형의";
$X_VIGNETTE ="소품";
$X_SHAVE="깎다";
$X_TRIM3 ="깎다3%";
$X_TRIM ="깎다";
$X_BORDER ="테두리";
$X_ARTFRAME ="예술 프레임";
$X_BLENDFRAME="프레임 조화";
$X_EDGE3DUP ="+ 가장자리 3D";
$X_EDGE3DDOWN ="- 가장자리 3D";
$X_EDGE="3D";
$X_BUTTON ="버튼";
$X_LABEL ="분류하다";
$X_BORDERTEXT ="국경 텍스트";
$X_STAMPTEXT ="우표 텍스트";
$X_GLITTERTEXT ="텍스트 빛나는";
$X_WATERMARK ="양수표";
$X_POSTER ="포스터";
$X_RESIZE="크기";
$X_RESIZEPERCENT ="%";
$X_RESIZEPIXELS ="픽셀";
$X_THUMBNAIL ="축소형";
$X_FILEKBSIZE="크기를 줄입니다";
$X_REDUCE="를 줄입니다";
$X_INSTANTREDUCE="즉시 감소";


$X_MIX ="섞다";
$X_ANIMATE ="생기있게하다";
$X_FRAMEANIMATION ="생기있게하다";
$X_VIBRATE="설레다";
$X_SCROLL="두루마리에 쓰다";
$X_SPIN ="돌리다";
$X_REFLECT="반사";
$X_PIMP ="반짝 거림";
$X_DEFORM="변형되다";
$X_3DANIMATION ="3D생기";
$X_POWERMORPH ="모핑";
$X_THEMATRIX="매트릭스";
$X_COMBINE= "결합";
$X_BLENDIMAGES ="이미지를 혼합";
$X_COOKIE ="사람";
$X_JIGSAW="실톱";
$X_MONTAGE ="몽타주";
$X_WORLDMIX ="세계 믹스";
$X_MAGAZINE ="잡지";
$X_FIREANDRAIN ="화재 및 비";
$X_COLORSWAP ="컬러 스왑";
$X_BLACKANDWHITE ="흑백의";
$X_COLORIZE="색의";
$X_COLORWASH ="수성 페인트";
$X_BLEACH ="표백";
$X_HEATMAP="히트지도";
$X_AVATAR ="화신";
$X_PHOTOTOCARTOON ="만화";


$X_CREATE="생성";
$X_LAYER ="층";
$X_TRANSPARENT ="투명한";
$X_TRANSPARENTBATCH ="투명한+";
$X_TRANSLUCENT ="반투명의";
$X_BEND ="굽히다";
$X_SWIRL ="아찔 아찔하다";
$X_IMPLODE="내파하다";
$X_EXPLODE="폭발하다";
$X_STRETCH ="펴다";
$X_WAVE ="웨이브";
$X_MUTATE="돌연변이";
$X_MELT="녹이다";
$X_PIXELATE="픽셀";
$X_SPLICE ="맞대어 잇다";
$X_FRACTAL ="프랙탈";
$X_TIMETUNNEL ="터널";
$X_FOSSILIZE="화석으로되다";
$X_3DSHAPE="형성하다 3D";
$X_ARTISTIC ="예술적인";
$X_OILPAINT ="오일 페인트";
$X_PENCIL ="연필로 쓰다";
$X_CHARCOAL ="목탄으로 그리다";
$X_ABSTRACT ="추상하다";
$X_BLACKLIGHT ="검은 빛";
$X_PSYCHEDELIC ="사이 키델릭";
$X_EMBOSS ="부풀 리다";
$X_ARTGALLERY ="미술관";
$X_FEELLUCKY ="전 행운아에요";

$X_RETURNTOMAINPAGE ="기본 페이지로 돌아가기";
$X_LABEL ="라벨";
$X_CONVERT="변하게하다";
$X_SELECTED="선택된";
$X_EFFECT ="효과";
$X_LEVEL ="수평";
$X_LINE ="라인";
$X_LOOP ="고리를 만들다";
$X_FONT ="글꼴";
$X_FONTSIZE="글꼴 크기";
$X_FUZZ ="보풀이 나게하다";
$X_LOW ="1";
$X_MEDIUM ="2";
$X_HIGH ="3";
$X_WIDTH ="너비";
$X_LENGTH ="길이";
$X_REVERSEMORPHINGATEND ="끝에 반전";
$X_REVERSE="끝에 반전";


$X_CLICKTOLOADIMAGE ="이미지를 업로드하시기 바랍니다";
$X_DIMENSIONS ="치수";
$X_COLORCOUNT ="색상 개수";
$X_CLICKTOVIEWMAC ="";
$X_CLICKTOVIEWPC="";
$X_UNDO ="사용 브라우저를 다시 실행 취소 버튼을";

$X_LOADIMAGE ="하중 이미지";
$X_FILELOADED="이미지로드";
$X_FROMCOMPUTER ="컴퓨터에서";
//$X_FROMWEB ="ウェブからの負荷のURL（貼り付け";
$X_FROMWEB ="웹에서 (URL)";
$LOAD_HELP ="최대 파일 크기는 2 분입니다. 파일을 90 일 후에 삭제됩니다";
$X_OR ="또는";
$X_LOAD ="업로드";
$X_CLEAR ="취소하다";

$TRANS_HELP ="그리고 이미지를 클릭한 다음 변환을 누릅니다. 선택한 시점에서 색상은 투명 색상 것입니다 <P> <strong>- 또는</strong> <P> 수동으로 색상을 선택하고 변환을 클릭합니다. 선택한 색상은 투명 색상 것입니다.  <P><BR> 타겟 색상은 100 % 순수하지 않으면 인접 또는 유사 색상을 포함하는 경찰 옵션을 사용 <P><BR><P><BR>";

$X_SLOWNOTE ="옵션 및 이미지 복잡도에 따라이 작업을 실행하는 데 시간이 걸릴 수 있습니다. 기다려주십시오";


$X_DIRECTION ="방향";
$X_FILE ="파일";
$X_FIRSTIMAGEWHOLE ="첫번째 이미지 전체";
$X_HEIGHT ="고도";
$X_WIDTH ="너비";
$X_HOLES ="구멍";
$X_ORIENTATION ="정위";
$X_POSITION ="위치";
$X_PRESERVEASPECTRATIOは="가로 세로 비율을 유지";
$X_SELECTCOLOR ="색상 선택";
$X_SEPARATION ="분리";


$X_SPEED="속도";
$X_AUTORESIZE="자동으로 크기를 조정";
$X_SIZE="크기";
$X_BLENDIMAGE ="이미지를 혼합";
$X_BLENDLEVEL="수준을 혼합";
$X_COLORTITLEANDBORDER = $X_PICKCOLOR="색";
$X_COLORBACKGROUND = $X_PICKBACKGROUNDCOLOR="배경 색상";
$X_TITLE="직함";
$X_COLORTEXT="텍스트 색상";

$X_GEOMETRIC="기하학";


?>
