<?php
$X_PUZZLE="enigma";

$X_PURCHASE="Comprar";
$X_DAVIDHILL="David Hill";
$X_ELLIPSE="Elipse";
$X_FLOODFILL="Preencher";
$X_GRITTY="Arenoso";
$X_DEEPDREAM="Sonhar";

$X_NEWSPRINT="Jornal";

$X_BOUNDBOX="Ativar Seleção de Imagem";

$X_MAGNIFY="Ampliar";

$X_SKEW="Enviesado";
$X_ENRICH="Enriquecer";
$X_SKETCH="Esboço";


$X_BEAUTY="Beleza";

$X_DOWNLOAD="Baixar";

$X_WEBCAM="&#161; clique !";
$X_SNAPSHOT="câmera";
$X_SNAPSHOT2="";


$X_VIEWIMAGE="Ver Imagem";
$X_STAINEDGLASS="Vitral";
$X_CUT="Cortar";
$X_FACEOFF="Rosto";
$X_FACEHELP="(Use Your Mouse to Define the Face Area)";
$X_OVERLAY="Cobrir";

$X_ROLLIMAGE="Rolar";
$X_REDUCECOLOR="Reduzir Cor";
$X_GLITTER="Cintilar";
$X_GROOVY="Groovy";
$X_OUTLINE="Esboço";
$X_PEARL="Pérola";

$X_SHAPE = "Forma";

$X_STENCIL="Estampilha";

$X_KALEIDOSCOPE="Caleidoscópio";

$X_CAMERA="Câmera";

$X_HISTORY="História";
$X_DAYS="Dia";

$X_RAINBOW="Rainbow";


$X_WARP = "Deformar";
$X_ENHANCE = "Melhore";
$X_FORMAT = "Formato";
$X_GIF = "Converter GIF";
$X_JPG = "Converter JPG";
$X_PNG = "Converter PNG";
$X_BMP = "Converter BMP";
$X_ICO = "Converter ICO";
$X_INSTANTFIX = "Instantânea";
$X_HDR = "HDR";
$X_SMOOTH = "Alisar";
$X_BLUR = "Borrada";
$X_TEXTURE = "Textura";
$X_COLOR = "Cor";
$X_ADJUST = "Ajuste";
$X_MONOCHROME = "Monocromático";
$X_NEGATE = "Negativa";
$X_SEPIA = "Sépia";
$X_TINT = "Matiz";
$X_ACCENT = "Acentuação";
$X_CONTRAST = "Contraste";
$X_BRIGHTNESS = "Brilho";
$X_SHARPNESS = "Nitidez";
$X_SATURATION = "Saturação";
$X_HUE = "Matiz";

$X_HIGHER = "Aumenta";
$X_LOWER = "Diminuir";

$X_EDIT = "Editar";
$X_ROTATE = "Rotacionar";
$X_INSTANTROTATE = "Imediatamente";
$X_ORIENT = "Rotação";
$X_FLIPVERTICALLY = "Verticalmente";
$X_FLIPHORIZONTALLY = "Horizontalmente";
$X_CROP = "Cortar";
$X_RECTANGULAR = "Retângulo";
$X_VIGNETTE = "Vignette";
$X_SHAVE = "Aparar";
$X_TRIM3 = "Aparar 3%";
$X_TRIM = "Aparar";
$X_BORDER = "Borda";
$X_ARTFRAME = "Artístico";
$X_BLENDFRAME = "Imagem Mistura";
$X_EDGE3DUP = "Ascendente";
$X_EDGE3DDOWN = "Descendente";
$X_EDGE="3D";
$X_BUTTON = "Botão";
$X_LABEL = "Etiqueta";
$X_LABEL = "Rótulo";
$X_BORDERTEXT = "Borda Texto";
$X_STAMPTEXT = "Carimbo Texto";
$X_GLITTERTEXT = "Brilhante Texto";
$X_WATERMARK = "Marca d'água";
$X_POSTER = "Cartaz";
$X_RESIZE = "Redimensionar";
$X_RESIZEPERCENT = "Por Cento";
$X_RESIZEPIXELS = "Pixels";
$X_THUMBNAIL = "Miniatura";
$X_FILEKBSIZE = "Tamanho";
$X_REDUCE = "Reduzir";
$X_INSTANTREDUCE = "Instantânea";


$X_MIX = "Mistura";
$X_ANIMATE = "Animar";
$X_FRAMEANIMATION = "Animação";
$X_VIBRATE = "Vibração";
$X_SCROLL = "Rolagem";
$X_SPIN = "Girar";
$X_REFLECT = "Refletir";
$X_PIMP = "Cintilante";
$X_DEFORM = "Deformar";
$X_3DANIMATION = "Animação 3D";
$X_POWERMORPH = "Mórficos";
$X_THEMATRIX = "Matriz";
$X_COMBINE = "Combinar";
$X_BLENDIMAGES = "Mistura";
$X_COOKIE = "Biscoito";
$X_JIGSAW = "Quebra-Cabeça";
$X_MONTAGE = "Colcha";
$X_WORLDMIX = "Mundo ";
$X_MAGAZINE = "Revista";
$X_FIREANDRAIN = "Fogo e Chuva";
$X_COLORSWAP = "Trocar";
$X_BLACKANDWHITE = "Preto e Branco";
$X_COLORIZE = "Ultravioleta";
$X_COLORWASH = "Lavar";
$X_BLEACH = "Espaço";
$X_HEATMAP = "Infravermelho";
$X_AVATAR = "Caricaturar";
$X_PHOTOTOCARTOON = "Caricaturar";


$X_CREATE = "Criar";
$X_LAYER = "Camada";
$X_TRANSPARENT = "Transparente";
$X_TRANSPARENTBATCH = "Transparente+";
$X_TRANSLUCENT = "Translúcido";
$X_BEND = "Dobre";
$X_SWIRL = "Redemoinho";
$X_IMPLODE = "Implodir";
$X_EXPLODE = "Explodir";
$X_STRETCH = "Estique";
$X_WAVE = "Onda";
$X_MUTATE = "Mutação";
$X_MELT = "Derreter";
$X_PIXELATE = "Pixelate";
$X_SPLICE = "Emendar";
$X_FRACTAL = "Fractal";
$X_TIMETUNNEL = "Túnel";
$X_FOSSILIZE = "Fóssil";
$X_3DSHAPE = "Forma 3D";
$X_ARTISTIC = "Artística";
$X_OILPAINT = "Pintura";
$X_PENCIL = "Lápis";
$X_CHARCOAL = "Carvão";
$X_ABSTRACT = "Abstrata";
$X_BLACKLIGHT = "Luz Negra";
$X_PSYCHEDELIC = "Psicodélico";
$X_EMBOSS = "Realçar";
$X_ARTGALLERY = "Galeria de Arte";
$X_FEELLUCKY = "Acaso";

$X_RETURNTOMAINPAGE = "Volte à Página Principal";

$X_CONVERT = "Converter";
$X_SELECTED = "Selecionado";

$X_EFFECT = "Efeito";
$X_LEVEL = "Nível";
$X_LINE = "Linha";
$X_LOOP = "Loop";
$X_FONT = "Fonte";
$X_FONTSIZE = "Tamanho";
$X_FUZZ = "Cotão";

$X_LOW = "Baixa";
$X_MEDIUM = "Médio";
$X_HIGH = "Alta";


$X_WAVEHEIGHT = "Altura";
$X_WAVEIMAGE = "Onda";
$X_WAVELENGTH = "Comprimento";
$X_WIDTH = "Largura";
$X_CLICKTOLOADIMAGE = "clique para carregar a imagem";
$X_DIMENSIONS = "Dimensões";
$X_COLORCOUNT = "Conde de Cor";
$X_CLICKTOVIEWMAC = "Clique para visualizar clique com o botão de controle para salvar";
$X_CLICKTOVIEWPC = "Clique para visualizar clique-direito para salvar";
$X_UNDO = "[o uso do navegador botão voltar para desfazer]";

$X_LOADIMAGE = "Carregar Imagem";
$X_FILELOADED = "Imagem carregado";
$X_FROMCOMPUTER = "carregar a partir do computador";
$X_FROMWEB = "carga da web (colar no URL)";
$LOAD_HELP = "O tamanho máximo do arquivo é de 2M <br> todas as imagens convertidas são automaticamente excluídos após 90 dias.";
$X_OR = "ou";
$X_LOAD = "Carga";
$X_CLEAR = "Clara";

$TRANS_HELP = "Clique sobre a imagem e clique em Convert A cor do ponto que você selecionou será a cor transparente <p><strong> -.. Ou.. - </strong> <P> manualmente escolher uma cor e clique em Converter. A cor escolhida será a cor transparente.";
$TRANSLUCENT_HELP = "Clique sobre a imagem e clique em Convert A cor do ponto que você selecionou será a cor translúcida <P> -.. Ou -. <P> Manualmente escolher uma cor e clique em Converter A cor escolhida será a translúcido.";
$X_SLOWNOTE = "dependendo das opções e da complexidade da imagem, esta operação pode demorar até um minuto para executar";


$X_3D = "3D";
$X_3DIMAGE = "Imagem 3D";
$X_3DANIMATED = "animado em 3D";
$X_3DROTATE = "3D Rotate Image";
$X_3DROTATED = "Rodado em 3D";
$X_3DSHAPEANIMATIONS = "Animações 3D Forma";
$X_90DEGREE = "rotação de 90 graus";
$X_ABSTRACTED = "Abstração";
$X_ACCENTIMAGECOLOR = "Cor Accent";
$X_AREACOLORCHANGED = "Cor área mudou";
$X_AREACOLORCHANGED = "Cor área mudou";
$X_ARTISTICFRAME = "Frame Artística";
$X_ARTTYPE = "Tipo de Arte";
$X_AUTORESIZE=  "Auto Redimensionar";
$X_BENDIMAGE = "Imagem Bend";
$X_BENT = "Bent";
$X_BLEACHED = "branqueada";
$X_BLEND = "mistura";
$X_BLENDED = "mistura";
$X_BLENDEDBORDERIMAGE = "Imagem Border Blended";
$X_BLENDERIZED = "liquidificados";
$X_BLENDIMAGE = "Blend imagem";
$X_BLENDLEVEL = "Nível Blend";
$X_BORDERIMAGE = "Imagem de Fronteiras";
$X_BRIGHTNESSDECREASED = "Brilho Diminuiu";
$X_BRIGHTNESSINCREASED = "Brilho Maior";
$X_CARTOONIMAGE =  "Imagem dos desenhos animados";
$X_CHANGECOLORAREA = "Alterar a cor de uma área da imagem";
$X_CHARCOALED = "Charcoaled";
$X_COLORACCENTED = "Cor acentuados";
$X_COLORBACKGROUND = "Cor: fundo";
$X_COLOR = "Cor";
$X_NEWCOLOR = "Nova Cor";
$X_OLDCOLOR = "Cor Velho";
$X_COLOREDBORDER = "borda colorida";
$X_COLORIZED = "coloração";
$X_COLORSWAPPED = "Cores Swapped";
$X_COLORTEXT = "Cor: Texto";
$X_COLORTITLEANDBORDER = "Cor: Título e Fronteiras";
$X_COLORWASHED = "Cor lavado";
$X_CONTRASTDECREASED = "Contraste Diminuiu";
$X_CONTRASTINCREASED = "Contraste Maior";
$X_COOKIECUTTER = "Cookie Cuttered";
$X_COOKIECUTTERIMAGE = "Imagem pré-fabricadas";
$X_CROPIMAGE = "Crop Image";
$X_CROPPED = "cortada";
$X_CURVATURE = "curvatura";
$X_DEFORMED = "deformadas";
$X_DEFORMIMAGE = "Imagem Deform";
$X_DENSITY = "densidade";
$X_DIRECTION = "Sentido";
$X_EMBOSSED = "gravado";
$X_ENCIRCLED = "Cercado";
$X_ENTERTHEMATRIX = "Enter the Matrix";
$X_EXPLODED = "explodiu";
$X_EXPLODEIMAGE = "Explode a imagem";
$X_FILE = "Arquivo";
$X_FIRSTIMAGEWHOLE = "Imagem Inteira";
$X_FLIPPEDHORIZONTALLY = "invertido horizontalmente";
$X_FLIPPEDVERTICALLY = "virado verticalmente";
$X_FOSSILIZEIMAGE = "fossilizar imagem";
$X_FOSSILIZED = "fossilizada";
$X_FRACTALIZED = "fractalizada";
$X_FRAMES = "Frames";
$X_GLITTERLABEL = "Label Glitter";
$X_HDRENERGIZED = "HDR Energizada";
$X_HEATMAPPED = "Heat mapeada";
$X_HEIGHT = "Altura";
$X_WIDTH = "Largura";
$X_HOLES = "Buracos Realidade";
$X_HUEDECREASED = "Matiz Diminuiu";
$X_HUEINCREASED = "Matiz Maior";
$X_IMAGEBUTTON = "Botão de Imagem";
$X_IMAGEFRACTAL = "Fractal Image";
$X_IMAGESPLICE = "Splice Imagem";
$X_IMPLODED = "implodiu";
$X_IMPLODEIMAGE = "implodir a imagem";
$X_INSTANTFIXED = "Instant fixo";
$X_JIGSAWIMAGE = "Imagem Jigsaw";
$X_JUMPINESS = "Nervosismo";
$X_MAGAZINEMIX = "Mix Magazine";
$X_MAKETRANSPARENT = "Faça parte da imagem transparente";
$X_MAKETRANSLUCENT = "Faça parte da imagem transparente";
$X_MATRIX = "Matrix";
$X_MELTED = "derretido";
$X_MELTIMAGE = "Melt imagem";
$X_MIRRORIMAGE = "Mirror Image";
$X_MONOCHROMED = "Monochromed";
$X_MONTAGEIMAGE = "Imagem Montage";
$X_MORPHED = "Mórficos";
$X_MORPHIMAGE = "Imagem Morph";
$X_MOTIVATIONALPOSTER = "Poster Motivacional";
$X_MUTATED = "Mutantes";
$X_MUTATEIMAGE = "Imagem Mutação";
$X_NEGATED = "Negar";
$X_ORIENTATION = "Orientação";
$X_PAINTED = "Pintado";
$X_PAINT = "Imagem Paint";
$X_PENCILLED = "Pencilled";
$X_PICKBACKGROUNDCOLOR = "Fundo";
$X_PICKCOLOR = "Cor";
$X_PIMPED = "Pimped";
$X_PIMPIMAGE = "Imagem Pimp";
$X_PIXELLATED = "pixelizadas";
$X_PIXELLATED = "pixelizadas";
$X_PIXELLATE = "Pixellate";
$X_POPART = "Pop Art";
$X_POSITION = "Posição";
$X_PRESERVEASPECTRATIO = "Preserve Aspect Ratio";
$X_RAISEDOWN = "3D borda inferior";
$X_RAISEUP = "Raise 3D Edge";
$X_RANDOMLYANIMATE = "aleatoriamente Animar";
$X_RANDOMYOUFELTUCKY = "Random - Você se sentiu com sorte";
$X_REDUCEBYAPPROXIMATE = "Reduzir em (aproximado)";
$X_REDUCEFILESIZE = "Reduzir tamanho do arquivo de imagem";
$X_REFLECTED = "refletido";
$X_REFLECTIMAGE = "refletir a imagem";
$X_RESIZEIMAGEPIXELS = "Image Resize (em pixels)";
$X_REVERSEMORPHINGATEND = "Reversa";
$X_REVERSE= "Reversa";
$X_RIPPLESIZES = "Tamanhos Ripple";
$X_ROTATED = "rodado";
$X_ROTATED = "rodado";
$X_ROTATEIMAGE = "Rodar imagem";
$X_SATURATIONDECREASED = "Saturação Diminuiu";
$X_SATURATIONINCREASED = "A crescente saturação";
$X_SCROLLED = "deslocada";
$X_SCROLLIMAGE = "Scroll Image";
$X_SELECTCOLOR = "Selecionar Cor";
$X_SEPARATION = "separação";
$X_SEPIATONED = "cor sépia";
$X_SETTING = "Ambiente";
$X_SHARPNESSDECREASED = "Nitidez Diminuiu";
$X_SHARPNESSINCREASED = "Nitidez Maior";
$X_SHAVED = "Barbear ";
$X_SHAVEIMAGE = "Barbear";
$X_SHAVE = "Barbear";
$X_SIZE = "Tamanho";
$X_SOLARIZE = "Solarize imagem";
$X_SPECIALEFFECTS = "efeitos especiais";
$X_SPEED = "Velocidade";
$X_SPINIMAGE = "Spin imagem";
$X_SPREAD = "Spread";
$X_SPUN = "Spun";
$X_STAMPTEXTINTOIMAGE = "Selo de texto em imagem";
$X_STRETCHED = "esticado";
$X_STRETCHIMAGE = "Imagem Stretch";
$X_SWIRLED = "rodado";
$X_SWIRLIMAGE = "Image Swirl";
$X_TARGETIMAGE = "imagem de destino";
$X_TEXTURED = "Textured";
$X_THUMBNAILED = "miniaturizadas";
$X_TINTED = "fumê";
$X_TINTLEVEL = "Nível Matiz";
$X_TITLE = "Título";
$X_TRANSLUCENCY = "translucidez";
$X_TRANSLUCENTADDED = "translúcido Adicionado";
$X_TRANSPARENCYADDED = "aumento da transparência";
$X_TRIMMED = "imagem recortada";
$X_TWILIGHT = "Crepúsculo";
$X_VIBRATED = "vibrado";
$X_VIBRATEIMAGE = "Imagem Vibrar";
$X_VIGNETTED = "vinhetas";
$X_WATERMARKIMAGE = "Image Watermark";
$X_WAVED = "galápagos";

$X_GEOMETRIC="Geométrico";



?>
