<?php 
$X_PUZZLE="головоломка";

$X_PURCHASE="купить";
$X_DAVIDHILL="античный";
$X_ELLIPSE="эллипс";
$X_FLOODFILL="наводнение";
$X_GRITTY="Nесчаный";
$X_DEEPDREAM="мечта";

$X_NEWSPRINT="газета";

$X_BOUNDBOX="Активируйте Выбор изображения";

$X_MAGNIFY="увеличивать";

$X_SKEW="косой";
$X_ENRICH="обогащать";
$X_SKETCH="эскиз";


$X_BEAUTY="красота";

$X_DOWNLOAD="скачать";

$X_WEBCAM="Веб-камера";
$X_SNAPSHOT="камера";
$X_SNAPSHOT2="";


$X_VIEWIMAGE="Просмотр изображения";
$X_STAINEDGLASS="цветное стекло";
$X_CUT="вырезать";
$X_FACEOFF="лицо";
$X_FACEHELP="(Use Your Mouse to Define the Face Area)";
$X_OVERLAY="наложение";

$X_ROLLIMAGE="ролл";
$X_REDUCECOLOR="уменьшить";
$X_GLITTER="блеск";
$X_GROOVY="заводной";
$X_OUTLINE="набросок";
$X_PEARL="жемчужный";

$X_SHAPE = "форма";
$X_STENCIL="трафарет";

$X_KALEIDOSCOPE="калейдоскоп";

$X_CAMERA="камера";

$X_HISTORY="история";
$X_DAYS="дней";

$X_RAINBOW="Rainbow";


$X_WARP = "коробить";
$X_ENHANCE = "повышения";
$X_FORMAT = "Формат";
$X_GIF = "GIF";
$X_JPG = "JPG";
$X_PNG = "PNG";
$X_BMP = "BMP";
$X_ICO = "ICO";
$X_INSTANTFIX = "быстро исправить";
$X_HDR = "активизировать";
$X_SMOOTH = "гладкое";
$X_BLUR = "размытия";
$X_TEXTURE = "текстура";
$X_COLOR = "Цвет";
$X_ADJUST = "Настройка";
$X_MONOCHROME = "монохромный";
$X_NEGATE = "Отрицание";
$X_SEPIA = "сепия";
$X_TINT = "Тон";
$X_ACCENT = "Акцент";
$X_CONTRAST = "Контраст";
$X_BRIGHTNESS = "Яркость";
$X_SHARPNESS = "Резкость";
$X_SATURATION = "Насыщенность";
$X_HUE = "Тон";

$X_HIGHER = "увеличение";
$X_LOWER = "уменьшение";

$X_EDIT = "Изменить";
$X_ROTATE = "Восток";
$X_INSTANTROTATE = "мгновенно";
$X_ORIENT = "Восток";
$X_FLIPVERTICALLY = "вертикальное";
$X_FLIPHORIZONTALLY = "горизонтальной";
$X_CROP = "Обрезать";
$X_RECTANGULAR = "Прямоугольный";
$X_VIGNETTE = "формы";
$X_SHAVE = "бритья";
$X_TRIM3 = "Отделка 3%";
$X_TRIM = "Отделка";
$X_BORDER = "объединить";
$X_ARTFRAME = "Искусство ";
$X_BLENDFRAME = "Смесь";
$X_EDGE3DUP = "3D До";
$X_EDGE3DDOWN = "3D Вниз";
$X_EDGE="3D";
$X_BUTTON = "Кнопка";
$X_LABEL = "Метка";
$X_BORDERTEXT = "пограничной";
$X_STAMPTEXT = "Печать текста";
$X_GLITTERTEXT = "Блеск Текст";
$X_WATERMARK = "водяных знаков";
$X_POSTER = "Плакат";
$X_RESIZE = "размер";
$X_RESIZEPERCENT = "%";
$X_RESIZEPIXELS = "пиксели";
$X_THUMBNAIL = "миниатюрные";
$X_FILEKBSIZE = "Файл KB Размер";
$X_REDUCE = "Уменьшить";
$X_INSTANTREDUCE = "мгновенно";


$X_MIX = "Смеси";
$X_ANIMATE = "анимации";
$X_FRAMEANIMATION = "кадр анимации";
$X_VIBRATE = "вибрировать";
$X_SCROLL = "прокрутки";
$X_SPIN = "спина";
$X_REFLECT = "Отражение";
$X_PIMP = "Блеск";
$X_DEFORM = "Деформировать";
$X_3DANIMATION = "3D анимации";
$X_POWERMORPH = "mорфинг";
$X_THEMATRIX = "mатрица";
$X_COMBINE = "сочетать";
$X_BLENDIMAGES = "смешивать";
$X_COOKIE = "Печенье";
$X_JIGSAW = "головоломка";
$X_MONTAGE = "mонтаж";
$X_WORLDMIX = "мир";
$X_MAGAZINE = "Журнал";
$X_FIREANDRAIN = "огонь и дождь";
$X_COLORSWAP = "своп";
$X_BLACKANDWHITE = "Черный Белый";
$X_COLORIZE = "сдвиг";
$X_COLORWASH = "Уош";
$X_BLEACH = "отбеливатель";
$X_HEATMAP = "ИК-порт";
$X_AVATAR = "аватар";
$X_PHOTOTOCARTOON = "мультипликация";


$X_CREATE = "Создать";
$X_LAYER = "cлой";
$X_TRANSPARENT = "прозрачный";
$X_TRANSPARENTBATCH = "прозрачный+";
$X_TRANSLUCENT = "полупрозрачный";
$X_BEND = "изогнутый";
$X_SWIRL = "водоворот";
$X_IMPLODE = "контракта";
$X_EXPLODE = "взорвать";
$X_STRETCH = "растягивать";
$X_WAVE = "Волна";
$X_MUTATE = "мутировать";
$X_MELT = "расплава";
$X_PIXELATE = "пиксель";
$X_SPLICE = "сращивания";
$X_FRACTAL = "фрактал";
$X_TIMETUNNEL = "туннель";
$X_FOSSILIZE = "закоснеть";
$X_3DSHAPE = "3D-форма";
$X_ARTISTIC = "художественное";
$X_OILPAINT = "масло";
$X_PENCIL = "Карандаш";
$X_CHARCOAL = "уголь";
$X_ABSTRACT = "абстрактное";
$X_BLACKLIGHT = "черного света";
$X_PSYCHEDELIC = "психоделический";
$X_EMBOSS = "выбито";
$X_ARTGALLERY = "галерея";
$X_FEELLUCKY = "случайные";

$X_RETURNTOMAINPAGE = "вернуться на главную страницу";

$X_CONVERT = "перевести";
$X_SELECTED = "Избранное";

$X_EFFECT = "Эффект";
$X_LEVEL = "Уровень";
$X_LINE = "Строка";
$X_LOOP = "итераций";
$X_FONT = "Шрифт";
$X_FONTSIZE = "Размер шрифта";
$X_FUZZ = "пух";

$X_LOW = "1";
$X_MEDIUM = "2";
$X_HIGH = "3";

$X_WAVEHEIGHT = "высоту";
$X_WAVEIMAGE = "Волна изображения";
$X_WAVELENGTH = "Длина волны";
$X_WIDTH = "Ширина";
$X_CLICKTOLOADIMAGE = "загрузить изображение";
$X_DIMENSIONS = "Размеры";
$X_COLORCOUNT = "Цвет Граф";
$X_CLICKTOVIEWMAC = "Просмотреть управления кнопкой мыши, чтобы сохранить";
$X_CLICKTOVIEWPC = "Нажмите для просмотра щелкните правой кнопкой мыши, чтобы сохранить";
$X_UNDO = "[браузер использовать кнопку Назад, чтобы отменить]";

$X_LOADIMAGE = "Загрузить изображения";
$X_FILELOADED = "Файл загружен";
$X_FROMCOMPUTER = "с вашего компьютера";
$X_FROMWEB = "из сети Интернет (Вставить в URL)";
$LOAD_HELP = "использовать кнопку Обзор, чтобы найти нужный файл. Максимальный размер файла составляет 2,0.";
$X_OR = "или";
$X_LOAD = "нагрузки";
$X_CLEAR = "ясно";

$TRANS_HELP = "Нажмите на изображение, а затем выберите команду Преобразовать цвета в точке выбранной будет прозрачный цвет <P> <strong> -.. Или - </ STRONG> <P> вручную выбрать цвет и щелкните по кнопке. Цвет выбрали будет прозрачного цвета. <P> <BR> Если ваша цель цвет не 100% чисто, используйте опцию Fuzz включить цветов, смежных или аналогичных <P> <BR> <P> <BR> " ;
$TRANSLUCENT_HELP = "Нажмите на изображение, а затем выберите команду Преобразовать цвета в точке выбранной будет полупрозрачный цвет <P> -.. Или -. <P> Вручную выбрать цвет и щелкните по кнопке Цвет выбран будет полупрозрачный . цвет <P> <BR> <P> Если ваша цель цвет не 100% чисто, используйте опцию Fuzz включить цветов, смежных или аналогичных <BR> <P> ";
$X_SLOWNOTE = "в зависимости от опций и изображения сложность, эта операция может занять до минуты, чтобы запустить";


$X_3D = "3D";
$X_3DIMAGE = "3D-изображение";
$X_3DANIMATED = "3D Animated";
$X_3DROTATE = "3D Поворот изображения";
$X_3DROTATED = "Повернуто 3D";
$X_3DSHAPEANIMATIONS = "3D Анимация формы";
$X_90DEGREE = "ротацией на 90 градусов";
$X_ABSTRACTED = "отведенной";
$X_ACCENTIMAGECOLOR = "Акцент цветном изображении";
$X_AREACOLORCHANGED = "Площадь измененный цвет";
$X_AREACOLORCHANGED = "Площадь измененный цвет";
$X_ARTISTICFRAME = "Художественная рамка";
$X_ARTTYPE = "Искусство типа";
$X_AUTORESIZE = "Auto Resize";
$X_BENDIMAGE = "Бенд изображения";
$X_BENT = "Бент";
$X_BLEACHED = "отбеленная";
$X_BLEND = "смешивать";
$X_BLENDED = "смешанная";
$X_BLENDEDBORDERIMAGE = "Смешанное краям изображения";
$X_BLENDERIZED = "Blenderized";
$X_BLENDIMAGE = "Blend изображения";
$X_BLENDLEVEL = "Blend уровня";
$X_BORDERIMAGE = "Граница изображения";
$X_BRIGHTNESSDECREASED = "Яркость Снижение";
$X_BRIGHTNESSINCREASED = "Яркость Увеличение";
$X_CARTOONIMAGE = "мультфильм изображения";
$X_CHANGECOLORAREA = "Изменение цвета одной области изображения";
$X_CHARCOALED = "Charcoaled";
$X_COLORACCENTED = "Цвет акцентированная";
$X_COLORBACKGROUND = "Цвет: Фон";
$X_COLOR = "Цвет";
$X_NEWCOLOR = "Новый цвет";
$X_OLDCOLOR = "Старый цвета";
$X_COLOREDBORDER = "цветной рамкой";
$X_COLORIZED = "Раскрашенная";
$X_COLORSWAPPED = "Цвета поменялся";
$X_COLORTEXT = "Цвет: Текст";
$X_COLORTITLEANDBORDER = "Цвет: Название и границе";
$X_COLORWASHED = "Цвет мытый";
$X_CONTRASTDECREASED = "Контрастность Снижение";
$X_CONTRASTINCREASED = "Контрастность Увеличение";
$X_COOKIECUTTER = "Cookie Cuttered";
$X_COOKIECUTTERIMAGE = "Cookie Cutter изображения";
$X_CROPIMAGE = "Обрезать изображение";
$X_CROPPED = "обрезанное";
$X_CURVATURE = "кривизны";
$X_DEFORMED = "Деформированные";
$X_DEFORMIMAGE = "Deform изображения";
$X_DENSITY = "Плотность";
$X_DIRECTION = "Направление";
$X_EMBOSSED = "выбитый";
$X_ENCIRCLED = "Encircled";
$X_ENTERTHEMATRIX = "Введите Матрица";
$X_EXPLODED = "взорвался";
$X_EXPLODEIMAGE = "Explode изображения";
$X_FILE = "Файл";
$X_FIRSTIMAGEWHOLE = "1 все изображение";
$X_FLIPPEDHORIZONTALLY = "Отражено по горизонтали";
$X_FLIPPEDVERTICALLY = "отражено по вертикали";
$X_FOSSILIZEIMAGE = "окаменелость изображения";
$X_FOSSILIZED = "Ископаемые";
$X_FRACTALIZED = "Fractalized";
$X_FRAMES = "Кадры";
$X_GLITTERLABEL = "Сверкающий";
$X_HDRENERGIZED = "HDR Energized";
$X_HEATMAPPED = "Тепло Подключенные";
$X_HEIGHT = "высоту";
$X_WIDTH = "ширину";
$X_HOLES = "Реальность дыры";
$X_HUEDECREASED = "Hue Снижение";
$X_HUEINCREASED = "Hue Увеличение";
$X_IMAGEBUTTON = "Кнопка с изображением";
$X_IMAGEFRACTAL = "Изображение фрактал";
$X_IMAGESPLICE = "Изображение сращивания";
$X_IMPLODED = "взорвался";
$X_IMPLODEIMAGE = "Implode изображения";
$X_INSTANTFIXED = "Мгновенное Исправлена ​​ошибка";
$X_JIGSAWIMAGE = "Jigsaw изображения";
$X_JUMPINESS = "нервозности";
$X_LABEL = " метка";
$X_MAGAZINEMIX = "Журнал Mix";
$X_MAKETRANSPARENT = "сделать часть изображения прозрачной";
$X_MAKETRANSLUCENT = "сделать часть изображения прозрачной";
$X_MATRIX = "Матрица";
$X_MELTED = "Расплавленный";
$X_MELTIMAGE = "Melt изображения";
$X_MIRRORIMAGE = "Зеркальное отражение";
$X_MONOCHROMED = "Monochromed";
$X_MONTAGEIMAGE = "Монтаж изображения";
$X_MORPHED = "превратился";
$X_MORPHIMAGE = "Morph изображения";
$X_MOTIVATIONALPOSTER = "мотивационных плакатов";
$X_MUTATED = "Мутировавшая";
$X_MUTATEIMAGE = "Mutate изображения";
$X_NEGATED = "Отрицательные";
$X_ORIENTATION = "Ориентация";
$X_PAINTED = "нарисовал";
$X_PAINT = "Краски изображения";
$X_PENCILLED = "Pencilled";
$X_PICKBACKGROUNDCOLOR = "Цвет фона";
$X_PICKCOLOR = "Цвет";
$X_PIMPED = "Pimped";
$X_PIMPIMAGE = "Pimp изображения";
$X_PIXELLATED = "пикселированные";
$X_PIXELLATED = "пикселированные";
$X_PIXELLATE = "Pixellate";
$X_POPART = "поп-арт";
$X_POSITION = "Позиция";
$X_PRESERVEASPECTRATIO = "Сохранение пропорций";
$X_RAISEDOWN = "Нижняя 3D Edge";
$X_RAISEUP = "Поднимите Edge 3D";
$X_RANDOMLYANIMATE = "случайно анимации";
$X_RANDOMYOUFELTUCKY = "Случайные - Вы чувствовали Lucky";
$X_REDUCEBYAPPROXIMATE = "Сократить на (приблизительно)";
$X_REDUCEFILESIZE = "Уменьшение размера файлов изображений";
$X_REFLECTED = "отражается";
$X_REFLECTIMAGE = "Отражение изображения";
$X_RESIZEIMAGEPIXELS = "Изменить размер изображения (по пикселям)";
$X_REVERSEMORPHINGATEND = "Обратный Morphing На краю";
$X_REVERSE= "Обратный";
$X_RIPPLESIZES = "Ripple Размеры";
$X_ROTATED = "Повернуто";
$X_ROTATED = "Повернуто";
$X_ROTATEIMAGE = "Поворот изображения";
$X_SATURATIONDECREASED = "Насыщенность Снижение";
$X_SATURATIONINCREASED = "Насыщенность Увеличение";
$X_SCROLLED = "прокручивается";
$X_SCROLLIMAGE = "Прокрутка изображения";
$X_SELECTCOLOR = "Выберите цвет";
$X_SEPARATION = "Разделение";
$X_SEPIATONED = "сепия тона";
$X_SETTING = "Установка";
$X_SHARPNESSDECREASED = "Резкость Снижение";
$X_SHARPNESSINCREASED = "Резкость Увеличение";
$X_SHAVED = "Изображение бритая";
$X_SHAVEIMAGE = "Бритье изображения";
$X_SHAVE = "бритая";
$X_SIZE = "Размер";
$X_SOLARIZE = "Solarize изображения";
$X_SPECIALEFFECTS = "Специальные эффекты";
$X_SPEED = "Скорость";
$X_SPINIMAGE = "Spin изображения";
$X_SPREAD = "Spread";
$X_SPUN = "закрученная";
$X_STAMPTEXTINTOIMAGE = "Печать текста в изображение";
$X_STRETCHED = "натяжные";
$X_STRETCHIMAGE = "Stretch изображения";
$X_SWIRLED = "закрученного";
$X_SWIRLIMAGE = "Swirl изображения";
$X_TARGETIMAGE = "изображение цели";
$X_TEXTURED = "текстурированные";
$X_THUMBNAILED = "эскизы";
$X_TINTED = "Тонированные";
$X_TINTLEVEL = "Тон уровня";
$X_TITLE = "Название";
$X_TRANSLUCENCY = "Прозрачность";
$X_TRANSLUCENTADDED = "Светопрозрачные Добавлена";
$X_TRANSPARENCYADDED = "Прозрачность Добавлена";
$X_TRIMMED = "подстриженные изображения";
$X_TWILIGHT = "Сумерки";
$X_VIBRATED = "вибрированного";
$X_VIBRATEIMAGE = "Вибрация изображения";
$X_VIGNETTED = "Vignetted";
$X_WATERMARKIMAGE = "изображение водяного знака";
$X_WAVED = "Махал";

$X_GEOMETRIC="геометрический";


?>
