<?php
$X_PUZZLE="rompecabezas";

$X_PURCHASE="comprar";
$X_DAVIDHILL="David Hill";
$X_ELLIPSE="Elipse";
$X_FLOODFILL="inundació";
$X_GRITTY="Arenoso";
$X_DEEPDREAM="Sueña";

$X_NEWSPRINT="Periodico";

$X_BOUNDBOX="activar selección de imagen";

$X_MAGNIFY="Aumentar";

$X_SKEW="Sesgar";
$X_ENRICH="Enriquecer";
$X_SKETCH="Bosquejo";


$X_BEAUTY="Belleza";

$X_DOWNLOAD="descargar";

$X_WEBCAM="&#161; clic !";

$X_SNAPSHOT="cámara";
$X_SNAPSHOT2="";


$X_VIEWIMAGE="ver imagen";
$X_STAINEDGLASS="Vidrieras";
$X_CUT="Cortar";
$X_FACEOFF="Cara";
$X_FACEHELP="(Use Your Mouse to Define the Face Area)";
$X_OVERLAY="Superposición";

$X_ROLLIMAGE="Rodar";
$X_REDUCECOLOR="Reducir";
$X_GLITTER="Brillante";
$X_GROOVY="Groovy";
$X_OUTLINE="Esquema";
$X_PEARL="Perla";

$X_SHAPE = "Forma";

$X_STENCIL="Plantilla";

$X_KALEIDOSCOPE="Caleidoscopio";

$X_CAMERA="Cámara";

$X_HISTORY="historia";
$X_DAYS="Días";

$X_RAINBOW="Rainbow";
$X_ENHANCE="Mejora";

$X_FORMAT = "Formato";
$X_GIF = "GIF";
$X_JPG = "JPG";
$X_PNG = "PNG";
$X_BMP = "BMP";
$X_ICO = "ICO";
$X_INSTANTFIX = "Inmediatamente";
$X_HDR = "HDR";
$X_SMOOTH = "Alisar";
$X_BLUR = "Difuminar";
$X_TEXTURE = "Textura";
$X_COLOR = "Colorear";
$X_ADJUST = "Modifica";
$X_MONOCHROME = "Monocromo";
$X_NEGATE = "Negativo";
$X_SEPIA = "Sepia";
$X_TINT = "Matiz";
$X_ACCENT = "Acento";
$X_CONTRAST = "Contraste";
$X_BRIGHTNESS = "Brillo";
$X_SHARPNESS="Nitidez";
$X_SATURATION = "Saturación";
$X_HUE = "Tono";

$X_HIGHER = "Aumentar";
$X_LOWER = "Disminución";

$X_EDIT = "Editar";
$X_ROTATE = "Girar";
$X_INSTANTROTATE = "Instantánea";
$X_ORIENT = "Girar";
$X_FLIPVERTICALLY="Vertical";
$X_FLIPHORIZONTALLY = "Horizontal";
$X_CROP = "Recortar";
$X_RECTANGULAR = "Rectangular";
$X_VIGNETTE = "Viñeta";
$X_SHAVE = "afeitado";
$X_TRIM3 = "Recortar 3%";
$X_TRIM = "Recortar";
$X_BORDER = "Borde";
$X_ARTFRAME = "Arte";
$X_BLENDFRAME = "Imagen";
$X_EDGE3DUP = "3D Levantar";
$X_EDGE3DDOWN = "3D Inferior";
$X_EDGE="3D";
$X_BUTTON = "Botón";
$X_LABEL = "etiqueta";
$X_BORDERTEXT = "Texto Borde";
$X_STAMPTEXT = "Texto Sello";
$X_GLITTERTEXT = "Texto Brillante";
$X_WATERMARK = "Marca Agua";
$X_POSTER = "Cartel";
$X_RESIZE = "Tamaño";
$X_RESIZEPERCENT = "Por Ciento";
$X_RESIZEPIXELS = "Píxeles";
$X_THUMBNAIL = "Miniatura";
$X_FILEKBSIZE = "Archivo KB";
$X_REDUCE = "Reducir";
$X_INSTANTREDUCE = "Inmediatamente";


$X_MIX = "Mezclar";
$X_ANIMATE = "Animación";
$X_FRAMEANIMATION = "Animación";
$X_VIBRATE = "Vibración";
$X_SCROLL = "Desplácese";
$X_SPIN = "Hilado";
$X_REFLECT = "Reflexionar";
$X_PIMP = "Escarcha";
$X_DEFORM = "Deformación";
$X_3DANIMATION = "Animación 3D";
$X_POWERMORPH = "Morph";
$X_THEMATRIX = "Matrix";
$X_COMBINE = "Combinar";
$X_BLENDIMAGES = "Mezcla";
$X_COOKIE = "Galleta";
$X_JIGSAW = "Rompecabezas";
$X_MONTAGE = "Montaje";
$X_WORLDMIX = "Mundo";
$X_MAGAZINE = "Revista";
$X_FIREANDRAIN = "Fire & Rain";
$X_COLORSWAP = "Cambiar";
$X_BLACKANDWHITE = "Negro Blanco";
$X_COLORIZE = "Colorear";
$X_COLORWASH = "Lavado";
$X_BLEACH = "Blanqueado";
$X_HEATMAP = "Mapa";
$X_AVATAR = "Caricaturas";
$X_PHOTOTOCARTOON = "Caricaturas";


$X_CREATE = "Crear";
$X_LAYER = "Capa";
$X_TRANSPARENT = "Transparente";
$X_TRANSPARENTBATCH = "Transparente+";
$X_TRANSLUCENT = "Translúcida";
$X_BEND = "Curva";
$X_WARP="Deformar";
$X_SWIRL = "Remolino";
$X_IMPLODE = "Implosión";
$X_EXPLODE = "Explosión";
$X_STRETCH = "Estirar";
$X_WAVE = "Onda";
$X_MUTATE = "Mutado";
$X_MELT = "Fundir";
$X_PIXELATE = "Pixelizar";
$X_SPLICE = "Splice";
$X_FRACTAL = "Fractal";
$X_TIMETUNNEL = "Túnel";
$X_FOSSILIZE = "Fosilizar";
$X_3DSHAPE = "Forma 3D";
$X_ARTISTIC = "Artística";
$X_OILPAINT = "Pintura ";
$X_PENCIL = "Lápiz";
$X_CHARCOAL = "Carbón";
$X_ABSTRACT = "Abstracto";
$X_BLACKLIGHT = "Luz Negro";
$X_PSYCHEDELIC = "Psicodélico";
$X_EMBOSS = "Repujado";
$X_ARTGALLERY = "Galería Arte";
$X_FEELLUCKY = "Azar";

$X_CONVERT = "Convertir";
$X_SELECTED="Seleccionados";
$X_LOW = "Bajo";
$X_MEDIUM = "Medio";
$X_HIGH = "Alto";
$X_RED = "Rojo";
$X_GREEN = "Verde";
$X_BLUE = "Blue";
$X_YELLOW = "Amarillo";
$X_CYAN = "Cyan";
$X_MAGENTA = "Magenta";

$X_3D = "3D";
$X_3DIMAGE = "Imagen 3D";
$X_3DANIMATED = "Animación 3D";
$X_3DROTATE = "3D Rotación ";
$X_3DROTATED = "Girado 3D";
$X_3DSHAPEANIMATIONS = "Animaciones 3D";
$X_90DEGREE = "90 grados de rotación";
$X_ABSTRACT = "Abstracta";
$X_ABSTRACTED = "Fragmentos";
$X_ACCENTIMAGECOLOR = "Accent Color";
$X_AREACOLORCHANGED = "color Área de Cambio";
$X_AREACOLORCHANGED = "color Área de Cambio";
$X_ARTGALLERY = "Galería de Arte";
$X_ARTISTICFRAME = "marco artístico";
$X_ARTTYPE = "El arte de tipo";
$X_AUTORESIZE = "Cambiar el tamaño de Auto";
$X_BENDIMAGE = "Doble Imagen";
$X_BENT = "Bent";
$X_BLEACHED = "Blanqueados";
$X_BLEND = "Mezclar";
$X_BLENDED = "Mixta";
$X_BLENDEDBORDERIMAGE = "Imagen Frontera Mixta";
$X_BLENDERIZED = "licuadas";
$X_BLENDIMAGE = "Mezcla";
$X_BLENDIMAGES  = "Mezcla";
$X_BLENDLEVEL = "Mezcla Nivel";
$X_BORDERIMAGE = "Imagen de Fronteras";
$X_BRIGHTNESSDECREASED = "Brillo Disminución";
$X_BRIGHTNESSINCREASED = "El aumento de brillo";
$X_CARTOONIMAGE = "Caricaturas";
$X_CHANGECOLORAREA = "Cambiar el color de un área de la imagen";
$X_CHANGECOLORAREA = "Cambiar el color de un área de la imagen";
$X_CHARCOAL = "Carbón";
$X_CHARCOALED = "Charcoaled";
$X_COLORACCENTED = "color acentuados";
$X_COLORBACKGROUND = "color: de fondo";
$X_NEWCOLOR = "Color Nuevo";
$X_OLDCOLOR = "Color Viejo";
$X_COLOREDBORDER = "borde de color";
$X_COLORIZED = "Coloreada";
$X_COLORSWAP = "Cambio";
$X_COLORSWAPPED = "Colores intercambiado";
$X_COLORTEXT = "Texto";
$X_COLORTITLEANDBORDER = "color: Título y Frontera";
$X_COLORWASHED = "Lavada";
$X_CONTRASTDECREASED = "Contraste Disminución";
$X_CONTRASTINCREASED = "Contraste Mayor";
$X_COOKIECUTTER = "Galleta";
$X_COOKIECUTTERIMAGE = "Galleta";
$X_CROPIMAGE = "Recortar imagen";
$X_CROPPED = "recortada";
$X_CURVATURE = "Curvatura";
$X_DEFORMED = "deformados";
$X_DEFORMIMAGE = "Imagen de Deformación";
$X_DENSITY = "densidad";
$X_DIRECTION = "Dirección";
$X_EFFECT = "Efecto";
$X_EMBOSSED = "Repujado";
$X_ENCIRCLED = "Cercado";
$X_ENTERTHEMATRIX = "Enter the Matrix";
$X_EXPLODED = "explotado";
$X_EXPLODEIMAGE = "Explota la imagen";
$X_FILE = "Archivo";
$X_FIREANDRAIN = "Fuego Lluvia";
$X_FIRSTIMAGEWHOLE = "Toda la primera imagen";
$X_FLIPPEDHORIZONTALLY = "volteada horizontalmente";
$X_FLIPPEDVERTICALLY = "volteada verticalmente";
$X_FONT = "Fuente";
$X_FONT = "Fuente";
$X_FONTSIZE = "Tamaño de fuente";
$X_FOSSILIZEIMAGE = "fosilizan imagen";
$X_FOSSILIZED = "fosilizados";
$X_FRACTALIZED = "fractal";
$X_FRAMES = "Marcos";
$X_FUZZ = "pelusa";
$X_GLITTERLABEL = "Glitter multinacional";
$X_HDRENERGIZED = "HDR Energizado";
$X_HEATMAPPED = "Heat asignada";
$X_HEIGHT = "Altura";
$X_HOLES  = "Agujeros la realidad";
$X_HUEDECREASED = "Tono Disminución";
$X_HUEINCREASED = "tono mayor";
$X_IMAGEBUTTON = "imagen del botón";
$X_IMAGEFRACTAL = "fractal de la imagen";
$X_IMAGESPLICE = "Imagen de empalme";
$X_IMPLODED = "implosión";
$X_IMPLODEIMAGE = "Implosión imagen";
$X_INSTANTFIXED = "Instant fijo";
$X_JIGSAWIMAGE = "Imagen Jigsaw";
$X_JUMPINESS = "Nerviosismo";
$X_LABEL = "Etiqueta";
$X_LEVEL = "Nivel";
$X_LINE = "Línea";
$X_LOOP = "Iteraciones";
$X_MAGAZINEMIX = "Revista";
$X_MAKETRANSPARENT = "hacen parte de la imagen translúcida";
$X_MAKETRANSLUCENT = "hacen parte de la imagen translúcida";
$X_MATRIX = "Matriz";
$X_MELTED = "fundido";
$X_MELTIMAGE = "Melt imagen";
$X_MIRRORIMAGE = "Mirror Image";
$X_MONOCHROMED = "Monochromed";
$X_MONTAGEIMAGE = "Image Montage";
$X_MONTAGE = "Montaje";
$X_MORPHED = "se transformó";
$X_MORPHIMAGE = "Imagen Morph";
$X_MOTIVATIONALPOSTER = "Cartel de motivación";
$X_MUTATED = "mutado";
$X_MUTATEIMAGE = "Imagen mutado";
$X_NEGATED = "negada";
$X_NEWCOLOR = "color nuevo";
$X_ORIENTATION = "Orientación";
$X_PAINTED = "pintado";
$X_PAINT = "Imagen de la pintura";
$X_PENCILLED = "Pencilled";
$X_PENCIL = "Lápiz";
$X_PICKBACKGROUNDCOLOR = "Fondo";
$X_PICKCOLOR = "Colorear";
$X_PIMPED = "Pimped";
$X_PIMPIMAGE = "Pimp imagen";
$X_PIXELLATED = "pixelada";
$X_PIXELLATED = "pixelada";
$X_PIXELLATE = "Pixellate";
$X_POPART = "Arte Pop";
$X_POSITION = "Posición";
$X_PRESERVEASPECTRATIO = "Mantener relación de aspecto";
$X_RAISEDOWN = "Baja 3D Edge";
$X_RAISEUP = "Levante 3D Edge";
$X_RANDOMLYANIMATE = "Animar al azar";
$X_RANDOMYOUFELTUCKY = "aleatoria - Usted tuvo la suerte";
$X_REDUCEBYAPPROXIMATE = "reducir a la (aproximado)";
$X_REDUCEFILESIZE = "Reducir el tamaño del archivo de imagen";
$X_REFLECTED = "reflejada";
$X_REFLECTIMAGE = "reflejar la imagen";
$X_RESIZEIMAGEPIXELS = "tamaño de imagen (en píxeles)";
$X_REVERSEMORPHINGATEND = "Invertir Morphing En el fin";
$X_REVERSE= "Invertir";
$X_RIPPLESIZES = "Dimensiones Onda";
$X_ROTATED = "girado";
$X_ROTATED = "girado";
$X_ROTATEIMAGE = "Rotar imagen";
$X_SATURATIONDECREASED = "disminución de la saturación";
$X_SATURATIONINCREASED = "Saturación Mayor";
$X_SCROLLED = "Desplazamiento";
$X_SCROLLIMAGE = "Vaya imagen";
$X_SELECTCOLOR = "Colorear";
$X_SEPARATION = "Separación";
$X_SEPIATONED = "color sepia";
$X_SETTING = "Marco";
$X_SHARPNESSDECREASED = "Nitidez Disminución";
$X_SHARPNESSINCREASED = "Nitidez Mayor";
$X_SHAVED = "Imagen afeitado";
$X_SHAVEIMAGE = "Shave imagen";
$X_SHAVE = "afeitado";
$X_SIZE = "Tamaño";
$X_SOLARIZE = "Solarizar imagen";
$X_SPECIALEFFECTS = "Efectos especiales";
$X_SPEED = "Velocidad";
$X_SPINIMAGE = "Spin Imagen";
$X_SPREAD = "Difundir";
$X_SPUN = "Spun";
$X_STAMPTEXTINTOIMAGE = "Sello de texto en imágenes";
$X_STRETCHED = "estirada";
$X_STRETCHIMAGE = "Reducir la imagen";
$X_SWIRLED = "Swirled";
$X_SWIRLIMAGE = "Remolino";
$X_TARGETIMAGE = "imagen de destino";
$X_TEXTURED = "Textura";
$X_TEXTURE = "Imagen Textura";
$X_TEXTURE = "Textura";
$X_THUMBNAILED = "miniatura";
$X_TINTED = "Polarizado";
$X_TINTLEVEL = "el nivel de tinte";
$X_TINT = "Matiz";
$X_TITLE = "Título";
$X_TRANSLUCENCY = "Translucidez";
$X_TRANSLUCENTADDED = "translúcido Añadido";
$X_TRANSPARENCYADDED = "Transparencia Añadido";
$X_TRIMMED = "Imagen ajustada";
$X_TWILIGHT = "Crepúsculo";
$X_VIBRATED = "vibrado";
$X_VIBRATEIMAGE = "Imagen de vibración";
$X_VIGNETTED = "viñetas";
$X_WATERMARKIMAGE = "Imagen de marca de agua";
$X_WATERMARK = "Marca de Agua";
$X_WAVED = "Galápagos";
$X_WAVEHEIGHT = "Altura de onda";
$X_WAVEIMAGE = "Imagen de onda";
$X_WAVELENGTH = "Longitud de onda";
$X_WIDTH = "Ancho";

$X_CLICKTOLOADIMAGE = "Haga clic para cargar la imagen";
$X_DIMENSIONS  = "Dimensiones";
$X_COLORCOUNT = "color Conde";
$X_CLICKTOVIEWMAC  = " Haga clic para ver el control-clic en para guardar";
$X_CLICKTOVIEWPC  = " Haga clic para ver botón derecho del ratón para guardar";
$X_UNDO = "[navegador uso el botón Atrás para deshacer]";

$X_LOADIMAGE = "Cargar Imágenes";
$X_FILELOADED = "archivo cargado";
$X_FROMCOMPUTER = "Desde el ordenador (Utilice el botón Examinar)";
$X_FROMWEB = "de la Web (Pegar en la URL)";
$LOAD_HELP = "tamaño máximo de archivo es de 2M <br> todas las imágenes convertidas se eliminan automáticamente después de 90 días.";

$X_LOAD = "Cargar";
$X_CLEAR = "Cancelar";
$X_OR="O";

$TRANS_HELP = "Haga clic en la imagen y luego haga clic en convertir el color en el punto seleccionado será el color transparente <p> <strong> - O - </strong> <P> manual de elegir un color y haga clic en Convertir. El color elegido será el color transparente. Si <P> <BR> su color blanco no es 100% puro, utilice la opción Pelusa para incluir los colores que son adyacentes o similar <P> <BR> <P> <BR> " ;

$TRANSLUCENT_HELP = "Haga clic en la imagen y luego haga clic en convertir el color en el punto seleccionado será el color translúcido <P> - O - <P> Manual de elegir un color y haga clic en Convertir El color elegido será el translúcida color";


$X_SLOWNOTE = "dependiendo de las opciones y la complejidad de la imagen, esta operación puede tardar hasta un minuto para correr";


$X_RETURNTOMAINPAGE = "Volver a la página principal";

$X_GEOMETRIC="Geométrico";


?>
