<?php
$X_PUZZLE="câu đố";

$X_PURCHASE="mua";
$X_DAVIDHILL="đồ cổ";
$X_ELLIPSE="hình bầu dục";
$X_FLOODFILL="điền lũ";
$X_GRITTY="can đảm";
$X_DEEPDREAM="giấc mơ";

$X_NEWSPRINT="báo";

$X_BOUNDBOX="Bấm Vào Đây";

$X_MAGNIFY="phóng đại";

$X_SKEW="nghiêng";
$X_ENRICH="làm giàu";
$X_SKETCH="phác thảo";


$X_BEAUTY="vẻ đẹp";

$X_DOWNLOAD="tải về";

$X_WEBCAM="webcam";
$X_SNAPSHOT="máy ảnh";
$X_SNAPSHOT2="";

$X_VIEWIMAGE="xem ảnh";
$X_STAINEDGLASS="ly";
$X_CUT="cắt";
$X_FACEOFF="khuôn mặt";
$X_FACEHELP="(Use Your Mouse to Define the Face Area)";
$X_OVERLAY="lớp phủ";

$X_ROLLIMAGE="lăn";
$X_REDUCECOLOR="giảm";
$X_GLITTER="lấp lánh";
$X_GROOVY="đợt sống mới";
$X_OUTLINE="vạch ra";
$X_PEARL="trân châu";
$X_SHAPE="hình ảnh";

$X_STENCIL="miếng kim thuộc mỏng";

$X_KALEIDOSCOPE="cảnh thay đổi luôn";

$X_CAMERA="máy quay video";

$X_HISTORY="lịch sử";
$X_DAYS="ngày";

$X_RAINBOW="Rainbow";

$X_WARP="biến dạng";
$X_FORMAT = "định dạng";
$X_GIF = "GIF";
$X_JPG = "JPG";
$X_PNG = "PNG";
$X_BMP = "BMP";
$X_ICO = "ICO";
$X_INSTANTFIX = "tức thì";
$X_ENHANCE="nâng cao";
$X_HDR = "HDR";
$X_SMOOTH="mịn";
$X_BLUR="mờ";
$X_TEXTURE="kết cấu";
$X_COLOR = "màu sắc";
$X_ADJUST="điều chỉnh";
$X_MONOCHROME="đơn sắc";
$X_NEGATE="phủ định";
$X_ACCENT="màu lọc";
$X_NEGATE="phủ định";
$X_SEPIA="màu nâu đỏ";
$X_TINT="màu sắc thái";
$X_CONTRAST="tương phản";
$X_BRIGHTNESS="độ sáng";
$X_SHARPNESS="sắc nét";
$X_SATURATION="bão hòa";
$X_HUE="hue";

$X_HIGHER="tăng";
$X_LOWER="giảm";

$X_EDIT="sửa";
$X_ROTATE="xoay";
$X_INSTANTROTATE="ngay lập tức xoay";
$X_ORIENT="định hướng";
$X_FLIPVERTICALLY="thẳng đứng";
$X_FLIPHORIZONTALLY="ngang";
$X_CROP="cắt";
$X_RECTANGULAR="hình chữ nhật";
$X_VIGNETTE="chân dung";
$X_SHAVE="cắt cạnh";
$X_TRIM3="cắt cạnh 3%";
$X_TRIM="cắt cạnh";
$X_LABEL="có nhãn";
$X_BORDER="biên&nbsp;giới";
$X_ARTFRAME="khung nghệ thuật";
$X_BLENDFRAME="pha trộn";
$X_EDGE3DUP="3D rìa (nâng lên)";
$X_EDGE3DDOWN="3D rìa (hạ xuống)";
$X_EDGE="3D";
$X_BUTTON="nút";
$X_BORDERTEXT="nhãn";
$X_STAMPTEXT="có nhãn";
$X_GLITTERTEXT="lấp lánh văn bản";
$X_WATERMARK="watermark";
$X_POSTER="poster";
$X_RESIZE="cỡ";
$X_RESIZEPERCENT="phần trăm";
$X_RESIZEPIXELS="pixels";
$X_THUMBNAIL="thu nhỏ";
$X_FILEKBSIZE="kích thước";
$X_REDUCE="giảm";
$X_INSTANTREDUCE="ngay lập tức giảm";


$X_MIX="pha";
$X_ANIMATE="hoạt hình";
$X_FRAMEANIMATION="hoạt hình";
$X_VIBRATE="rung";
$X_SCROLL="cuộn";
$X_SPIN="quay";
$X_REFLECT="phản ánh";
$X_PIMP="lấp lánh";
$X_DEFORM="làm hư";
$X_3DANIMATION="3D hoạt hình";
$X_POWERMORPH="morph";
$X_THEMATRIX="ma trận";
$X_COMBINE="kết hợp";
$X_BLEND="pha trộn";
$X_COOKIE="cookie";
$X_JIGSAW="khó xử";
$X_MONTAGE="montage";
$X_WORLDMIX="thế giới";
$X_MAGAZINE="tạp chí";
$X_FIREANDRAIN="cháy và mưa";
$X_COLORSWAP="trao đổi";
$X_BLACKANDWHITE="màu đen trắng";
$X_COLORIZE="thay đổi";
$X_COLORWASH="rửa";
$X_BLEACH="thuốc tẩy";
$X_HEATMAP="hồng ngoại";
$X_AVATAR="phim";
$X_PHOTOTOCARTOON="phim hoạt hình";


$X_CREATE="tạo";
$X_LAYER="cành cây";




$X_TRANSPARENT="minh bạch";
$X_TRANSPARENTBATCH="minh bạch +";
$X_TRANSLUCENT="Translucent";
$X_BEND="uốn cong";
$X_SWIRL="xoáy";
$X_IMPLODE="nổ -";
$X_EXPLODE="nổ +";
$X_STRETCH="biến dạng";
$X_WAVE="sóng";
$X_MUTATE="đột biến";
$X_MELT="tan chảy";
$X_PIXELATE="pixelate";
$X_SPLICE="cách nối dây";
$X_FRACTAL="quăn";
$X_TIMETUNNEL="đường hầm";
$X_FOSSILIZE="hóa thạch";
$X_3DSHAPE="hình ảnh 3D";
$X_ARTISTIC="nghệ&nbsp;thuật";
$X_OILPAINT="sơn";
$X_PENCIL="bút chì";
$X_CHARCOAL="than";
$X_ABSTRACT="trừu tượng";
$X_BLACKLIGHT="phổ";
$X_PSYCHEDELIC="điên";
$X_EMBOSS="dập nổi";
$X_ARTGALLERY="nghệ thuật học";
$X_FEELLUCKY="ngẫu nhiên kỳ lạ";


$X_RETURNTOMAINPAGE = "trở về trang chính";

$X_CONVERT="chuyển đổi";
$X_SELECTSETTING="chọn cài đặt";
$X_LOW="thấp";
$X_MEDIUM="trung bình";
$X_HIGH="cao";
$X_SELECTED = "được chọn";


$X_EFFECT="hiệu lực";
$X_LEVEL="lựa chọn";
$X_LINE="dòng";
$X_LOOP="lặp lại";
$X_FONT="font";
$X_FONTSIZE="kích thước";
$X_FUZZ="lông tơ";


$X_CLICKTOLOADIMAGE="tải hình";
$X_DIMENSIONS="kích thước";
$X_COLORCOUNT="màu";
$X_CLICKTOVIEWMAC="Bấm vào để xem bấm điều khiển để tiết kiệm";
$X_CLICKTOVIEWPC="Bấm vào để xem kích chuột phải để tiết kiệm";
$X_UNDO="[trình duyệt sử dụng nút quay lại để hoàn tác]";

$X_LOADIMAGE = "tải hình";
$X_FILELOADED = "tập tin tải";
$X_FROMCOMPUTER = "từ máy tính của bạn";
$X_FROMWEB = "từ các trang web (dán trong URL)";
$LOAD_HELP = "kích thước file tối đa là 2.0M.";
$X_OR = "hoặc";
$X_LOAD = "tải_lên";
$X_CLEAR = "rõ_ràng";



$TRANS_HELP = "Click vào hình ảnh và sau đó nhấp vào Chuyển đổi màu tại điểm bạn chọn sẽ được các màu trong suốt <P> <strong> -. HOẶC - </ strong> <P> thủ chọn một màu sắc và nhấp vào Chuyển đổi.. Các màu sắc được lựa chọn sẽ là màu trong suốt. <P> <BR> Nếu màu sắc mục tiêu của bạn không phải là 100% tinh khiết, sử dụng tùy chọn Fuzz để bao gồm các màu sắc được liền kề hoặc tương tự <P> <BR> <P> <BR> " ;
$X_SLOWNOTE = "tùy thuộc vào lựa chọn và phức tạp hình ảnh, hoạt động này có thể mất đến một phút để chạy";


$X_3D = "3D";
$X_3DIMAGE="3D Image";
$X_3DSHAPEANIMATIONS="3D Shape Animations";
$X_90DEGREE = "90 Degree Rotation";
$X_ACCENTIMAGECOLOR="Accent Image Color";
$X_AREACOLORCHANGED="Area Color Changed";
$X_AREACOLORCHANGED="Area Color Changed";
$X_ARTISTICFRAME = "Artistic Frame";
$X_ARTTYPE="Art Type";
$X_AUTORESIZE="thay đổi kích thước tự động";
$X_BENDIMAGE="Bend Image";
$X_BENT="Bent";
$X_BLEACHED = "Bleached";
$X_BLENDED="Blended";
$X_BLENDEDBORDERIMAGE="Blended Border Image";
$X_BLENDERIZED="Blenderized";
$X_BLENDIMAGE="pha trộn hình ảnh";
$X_BLENDLEVEL="cấp";
$X_BORDERIMAGE="biên giới hình ảnh";
$X_BRIGHTNESSDECREASED = "Brightness Decreased";
$X_BRIGHTNESSINCREASED = "Brightness Increased";
$X_CARTOONIMAGE="Cartoon Image";
$X_CHANGECOLORAREA="Change the color of one area of the image";
$X_CHARCOALED = "Charcoaled";
$X_COLORACCENTED="Color Accented";
$X_COLORBACKGROUND="Color: Background";
$X_COLOR="màu sắc";
$X_NEWCOLOR="màu mới";
$X_OLDCOLOR="màu cũ";
$X_COLOREDBORDER = "Colored Border";
$X_COLORIZED = "Colorized";
$X_COLORSWAP="trao đổi màu";
$X_COLORSWAPPED="Colors Swapped";
$X_COLORTEXT="Color: Text";
$X_COLORTITLEANDBORDER="Color: Title & Border";
$X_COLORWASHED = "Color Washed";
$X_CONTRASTDECREASED = "Contrast Decreased";
$X_CONTRASTINCREASED = "Contrast Increased";
$X_COOKIECUTTER="Cookie Cuttered";
$X_COOKIECUTTERIMAGE="Cookie Cutter Image";
$X_CROPIMAGE="Crop Image";
$X_CROPPED="Cropped";
$X_CURVATURE="Curvature";
$X_DEFORMED="Deformed";
$X_DEFORMIMAGE="Deform Image";
$X_DENSITY="Density";
$X_DIRECTION="Direction";
$X_EMBOSSED = "Embossed";
$X_ENCIRCLED="Encircled";
$X_ENTERTHEMATRIX="Enter the Matrix";
$X_EXPLODED="EXPLODED";
$X_EXPLODEIMAGE="Explode Image";
$X_FILE="hồ sơ";
$X_FIRSTIMAGEWHOLE="1st toàn bộ";
$X_FLIPPEDHORIZONTALLY="Flipped Horizontally";
$X_FLIPPEDVERTICALLY="Flipped Vertically";
$X_FOSSILIZEIMAGE="Fossilize Image";
$X_FOSSILIZED = "Fossilized";
$X_FRACTALIZED= "Fractalized";
$X_FRAMES="khung hình";
$X_GLITTERLABEL="Glitter Label";
$X_HDRENERGIZED = "HDR Energized";
$X_HEATMAPPED = "Heat Mapped";
$X_HEIGHT="cao";
$X_WIDTH="chiều rộng";
$X_HOLES="thực tế lỗ";
$X_HUEDECREASED = "Hue Decreased";
$X_HUEINCREASED = "Hue Increased";
$X_IMAGEBUTTON = "Image Button";
$X_IMAGEFRACTAL="Image Fractal";
$X_IMAGESPLICE="Image Splice";
$X_IMPLODED="Imploded";
$X_IMPLODEIMAGE="Implode Image";
$X_INSTANTFIXED = "Instant Fixed";
$X_JIGSAWIMAGE="Jigsaw Image";
$X_JUMPINESS="sự tăng vọt";
$X_MAGAZINEMIX="Magazine Mix";
$X_MAKETRANSPARENT = "Make Part Of Image Translucent";
$X_MAKETRANSLUCENT = "Make Part Of Image Translucent";
$X_MATRIX="ma trận";
$X_MELTED="Melted";
$X_MELTIMAGE="Melt Image";
$X_MIRRORIMAGE="Mirror Image";
$X_MONOCHROMED = "Monochromed";
$X_MONTAGEIMAGE="Montage Image";
$X_MORPHED="Morphed";
$X_MORPHIMAGE="Morph Image";
$X_MOTIVATIONALPOSTER="Motivational Poster";
$X_MUTATED="Mutated";
$X_MUTATEIMAGE="Mutate Image";
$X_NEGATED = "Negated";
$X_ORIENTATION="Orientation";
$X_PAINTED = "Painted";
$X_PAINT="Paint Image";
$X_PENCILLED = "Pencilled";
$X_PICKBACKGROUNDCOLOR="màu nền";
$X_PICKCOLOR="màu sắc";
$X_PIMPED="Pimped";
$X_PIMPIMAGE="Pimp Image";
$X_PIXELLATED="Pixellated";
$X_PIXELLATED = "Pixellated";
$X_PIXELLATE="Pixellate";
$X_POPART="Pop Art";
$X_POSITION="vị trí";
$X_PRESERVEASPECTRATIO="tỉ lệ";
$X_RAISEDOWN="Lower Edge 3D";
$X_RAISEUP="Raise Edge 3D";
$X_RANDOMLYANIMATE="Ngẫu nhiên sinh động";
$X_RANDOMYOUFELTUCKY="Random - You Felt Lucky";
$X_REDUCEBYAPPROXIMATE="Reduce By (Approximate)";
$X_REDUCEFILESIZE="Reduce Image File Size";
$X_REFLECTED="Reflected";
$X_REFLECTIMAGE="Reflect Image";
$X_RESIZEIMAGEPIXELS="Resize Image (By Pixels)";
$X_REVERSEMORPHINGATEND="ngược lại";
$X_REVERSE="đảo ngược";
$X_RIPPLESIZES="kích thước";
$X_ROTATED="Rotated";
$X_ROTATED = "Rotated";
$X_ROTATEIMAGE="Rotate Image";
$X_SATURATIONDECREASED = "Saturation Decreased";
$X_SATURATIONINCREASED = "Saturation Increased";
$X_SCROLLED="Scrolled";
$X_SCROLLIMAGE="Scroll Image";
$X_SELECTCOLOR = "màu sắc";
$X_SEPARATION="tách";
$X_SEPIATONED = "Sepia-Toned";
$X_SETTING="lựa chọn";
$X_SHARPNESSDECREASED = "Sharpness Decreased";
$X_SHARPNESSINCREASED = "Sharpness Increased";
$X_SHAVED = "Image Shaved";
$X_SHAVEIMAGE="Shave Image";
$X_SHAVE="Shaved";
$X_SIZE="kích thước";
$X_SOLARIZE="Solarize Image";
$X_SPECIALEFFECTS="Special Effects";
$X_SPEED="tốc độ";
$X_SPINIMAGE="Spin Image";
$X_SPREAD="Spread";
$X_SPUN="Spun";
$X_STAMPTEXTINTOIMAGE="Stamp Text into Image";
$X_STRETCHED="Streched";
$X_STRETCHIMAGE="Stretch Image";
$X_SWIRLED="Swirled";
$X_SWIRLIMAGE="Swirl Image";
$X_TARGETIMAGE="hình ảnh";
$X_TEXTURED="Textured";
$X_TEXTURE="kết cấu";
$X_THUMBNAILED = "Thumbnailed";
$X_TINTED="Tinted";
$X_TINTLEVEL="Tint Level";
$X_TITLE="Title";
$X_TRANSLUCENCY="Translucency";
$X_TRANSLUCENTADDED = "Translucent Added";
$X_TRANSPARENCYADDED = "Transparency Added";
$X_TRIMMED = "Trimmed Image";
$X_TWILIGHT="Twilight";
$X_VIBRATED="Vibrated";
$X_VIBRATEIMAGE="Vibrate Image";
$X_VIGNETTED = "Vignetted";
$X_WATERMARKIMAGE="Watermark Image";
$X_WAVED="Waved";


$X_GEOMETRIC="hình học";



?>
