<?php
print "<div id=\"phoneops4\">\n";
print "<table class=\"ops\" cellpadding=\"0\" cellspacing=\"10\">\n";
DisplayOp("Add Transparency To An Image","$X_LAYER","$X_TRANSPARENT","trans.php","");
DisplayOp("Add Transparency To An Image","","$X_TRANSPARENTBATCH","batchtrans.php","");
DisplayOp("Add Translucency To An Image","","$X_TRANSLUCENT","opacity.php","");
DisplayOp("Bend An Image","$X_WARP","$X_BEND","bend.php","");
DisplayOp("Swirl","","$X_SWIRL","swirl.php","","");
DisplayOp("Eplode","","$X_EXPLODE","explode.php","");
DisplayOp("Wave","","$X_WAVE","wave.php","");
DisplayOp("Fractalize","","$X_FRACTAL","fractal.php","");
DisplayOp("Splice","","$X_SPLICE","splice.php","");
DisplayOp("Random Face Melt","","$X_MELT","melt.php","");
DisplayOp("Piellate","","$X_PIXELATE","pixel.php","");
DisplayOp("Roll Image","","$X_ROLLIMAGE","roll.php","");
DisplayOp("kaleidoscope","","$X_KALEIDOSCOPE","k.php","");
DisplayOp("Face Mutate","","$X_MUTATE","mutate.php","");
DisplayOp("Stretch Pull","","$X_STRETCH","stretch.php","");
DisplayOp("Time Tunnel","","$X_TIMETUNNEL","timetunnel.php","");
DisplayOp("Fossilze An Image","","$X_FOSSILIZE","fossil.php","");
DisplayOp("3D Image","","$X_3DSHAPE","3D.php","");
DisplayOp("Sketch Image","$X_ARTISTIC","$X_SKETCH","sketch.php","");
DisplayOp("Pencil An Image","","$X_PENCIL","pencil.php","");
DisplayOp("Paint An Image","","$X_OILPAINT","paint.php","");
DisplayOp("David Hill Effect","","David Hill","davidhill.php","");
DisplayOp("Black Light Image","","$X_BLACKLIGHT","tricolor.php","");
DisplayOp("Stained Glass","","$X_STAINEDGLASS","glass.php","");
DisplayOp("Special Effects: Psychedelic","","$X_PSYCHEDELIC","lsd.php","");
//DisplayOp("Special Effects: Inscribe","","Inscribe","inscribe.php","");
DisplayOp("$X_SEPIA","","$X_SEPIA","sepia.php","");
DisplayOp("Emboss Image","","$X_EMBOSS","emboss.php","");
DisplayOp("Art Gallery","","$X_ARTGALLERY","artist.php","");
DisplayOp("I feel lucky","","$X_FEELLUCKY","randx.php","NA");
print "</table>\n";
print "</div>\n";
?>
