<?php
print "<div id=\"phoneops3\">\n";
print "<table class=\"ops\" cellpadding=\"0\" cellspacing=\"10\">\n";
DisplayOp("$X_ANIMATE","$X_ANIMATE","$X_FRAMEANIMATION","anim.php","");
DisplayOp("$X_POPART","","$X_POPART","popart.php","");
DisplayOp("Special Effects","","$X_VIBRATE","vibrate.php","");
DisplayOp("Special Effects: Scroll","","$X_SCROLL","scroll.php","");
DisplayOp("Special Effects: DVD","","$X_SPIN","spin.php","");
DisplayOp("Create Image Reflection","","$X_REFLECT","reflect.php","");
DisplayOp("Pimp The Image","","$X_PIMP","pimp.php","");
DisplayOp("Special Effects: Deform","","$X_DEFORM","deform.php","");
DisplayOp("Special Effects: 3D Animation","","$X_3DANIMATION","3DAnim.php","");
DisplayOp("Special Effects: Morph Two Images","","$X_POWERMORPH","m.php","");
DisplayOp("Special Effects: The Matrix","","$X_THEMATRIX","matrix.php","");
DisplayOp("Overlay Two Images","$X_COMBINE","$X_OVERLAY","overlay.php","");
DisplayOp("Ghost Blend Two Images","","$X_BLEND","blend.php","");
//DisplayOp("blank shape","","$X_SHAPE","shape.php","");
DisplayOp("groovy","","$X_GROOVY","groovy.php","");
DisplayOp("cookie cutter","","$X_COOKIE","cutter.php","");
DisplayOp("Jigsaw An Image","","$X_JIGSAW","jig.php","");
DisplayOp("Montage","","$X_MONTAGE","mont.php",""); 
DisplayOp("Image Mix","$X_MIX","$X_WORLDMIX","mix.php","");
DisplayOp("Magazine","","$X_MAGAZINE","mag.php","");
DisplayOp("Apply A Natural Effect","","$X_FIREANDRAIN","fire.php","");
DisplayOp("Swap Image Colors","$X_COLOR","$X_COLORSWAP","swapper.php","");
DisplayOp("Color Flood Fill","","Color Flood Fill","fill.php",""); 
DisplayOp("Wash Image Colors","","$X_COLORWASH","simplex.php","WASH"); 
DisplayOp("Colorize the Image","","$X_COLORIZE","colorize.php","");
DisplayOp("Charcoal Image","","$X_CHARCOAL","charcoal.php","");
DisplayOp("Bleach This Image","","$X_BLEACH","bleached.php","");
DisplayOp("Heat Map Solarize Image","","$X_HEATMAP","heatmap.php","");
DisplayOp("Black & White","","$X_BLACKANDWHITE","blackwhite.php","");
//DisplayOp("Turn a photo into a cartoon or avatar","$X_AVATAR","$X_PHOTOTOCARTOON","cartoon2.php","");
DisplayOp("Cartoon","$X_AVATAR", "$X_PHOTOTOCARTOON", "simplex.php","CARTOON");
//DisplayOp("Turn a photo into a cartoon or avatar","$X_AVATAR","$X_PHOTOTOCARTOON","cartoon.php","");
print "<tr><td></td></tr>\n";
print "</table>\n";
print "</div>\n";
?>
